CREATE SCHEMA IF NOT EXISTS app;

USE app;

CREATE TABLE IF NOT EXISTS ROL(
	ID_ROL INT NOT NULL,
	NOMBRE VARCHAR(45) NOT NULL,
	PRIMARY KEY(ID_ROL)
);

CREATE TABLE IF NOT EXISTS USUARIO(
	ID_USUARIO INT NOT NULL AUTO_INCREMENT,
	ID_ROL INT NOT NULL,
	NOMBRE VARCHAR(45) NOT NULL,
	ACTIVO CHAR(1),
	PRIMARY KEY(ID_USUARIO),
	FOREIGN KEY(ID_ROL) REFERENCES ROL(ID_ROL)
);